#!/usr/bin/env bash
# Environment defaults for Gitea smoke tests.
# Tokens are sourced from test/gitea/tokens.env (generated by docker/gitea-setup.sh).

export GIT_USERNAME=${GIT_USERNAME:-"me"}
export GITPROXY_API_KEY=${GITPROXY_API_KEY:-"change-me-in-production"}
export GITEA_URL=${GITEA_URL:-"http://localhost:3000"}
export GITEA_ADMIN_USER=${GITEA_ADMIN_USER:-"gitproxyadmin"}
export GITEA_ADMIN_PASSWORD=${GITEA_ADMIN_PASSWORD:-"Admin1234!"}

# Auto-source tokens.env if present (generated by docker/gitea-setup.sh).
_TOKENS_FILE="$(dirname "${BASH_SOURCE[0]}")/tokens.env"
if [ -f "${_TOKENS_FILE}" ]; then
    # shellcheck source=/dev/null
    source "${_TOKENS_FILE}"
fi
unset _TOKENS_FILE

resolve_gitea_pat() {
    GIT_PASSWORD="${GIT_PASSWORD:-${GITEA_TESTUSER_TOKEN:-}}"
    if [ -z "${GIT_PASSWORD}" ] && [ -f ~/.gitea-pat ]; then
        GIT_PASSWORD="$(cat ~/.gitea-pat)"
    fi
    if [ -z "${GIT_PASSWORD}" ]; then
        echo "ERROR: No test-user token found." >&2
        echo "       Run docker/gitea-setup.sh to generate tokens, or set GIT_PASSWORD / GITEA_TESTUSER_TOKEN." >&2
        exit 1
    fi
    export GIT_PASSWORD
}
