spring.application.name=jgit-proxy
management.endpoints.web.exposure.include=*
logging.level.web=DEBUG
#logging.level.org.eclipse.jgit=DEBUG
logging.level.com.github.coopernetes=DEBUG
git-proxy.github.fetch.authorised-owners=finos,coopernetes
