management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.finos.gitproxy: DEBUG
git-proxy:
  filters:
    github-user-authenticated:
      enabled: true
      order: 1
      operations:
        - PUSH
      required-auth-schemes: bearer, token, basic
      providers:
        - github
    whitelists:
      - enabled: true
        order: 5
        operations:
          - FETCH
          - PUSH
        providers:
          - gitlab
        slugs:
          - coopernetes/test-repo
        owners:
          - finosfoundation
        names:
          - hello-world
      - enabled: true
        order: 10
        operations:
          - PUSH
        owners:
          - finosfoundation
        providers:
          - gitlab
      - enabled: true
        order: 10
        operations:
          - PUSH
        slugs:
          - finos/git-proxy
        providers:
          - github
      - enabled: true
        order: 20
        operations:
          - FETCH
        owners:
          - finos
        providers:
          - github
      - enabled: true
        order: 30
        operations:
          - FETCH
          - PUSH
        slugs:
          - coopernetes/test-repo
          - coopernetes/test-repo2
        providers:
          - github