package org.finos.gitproxy.git;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.jgit.transport.ReceiveCommand;
import org.eclipse.jgit.transport.ReceivePack;
import org.finos.gitproxy.config.CommitConfig;
import org.finos.gitproxy.db.model.PushStep;
import org.finos.gitproxy.db.model.StepStatus;
import org.finos.gitproxy.validation.BlockedContentDiffCheck;
import org.finos.gitproxy.validation.Violation;

/**
 * Pre-receive hook that scans the diff content of incoming pushes for blocked literals and patterns. Runs after
 * {@link DiffGenerationHook} and re-uses the diff already stored in {@link PushContext} rather than regenerating it.
 *
 * <p>Only added lines (those prefixed with {@code +} in the unified diff) are scanned - deletions and context lines are
 * ignored. Violations are reported via sideband and recorded in the shared {@link ValidationContext}.
 */
@Slf4j
@RequiredArgsConstructor
public class DiffScanningHook implements GitProxyHook {

    private static final int ORDER = 300;

    private final CommitConfig commitConfig;
    private final ValidationContext validationContext;
    private final PushContext pushContext;

    @Override
    public void onPreReceive(ReceivePack rp, Collection<ReceiveCommand> commands) {
        // Re-use the diff already generated by DiffGenerationHook
        String diff = pushContext
                .getStepContent(DiffGenerationHook.STEP_NAME_PUSH_DIFF)
                .orElse(null);

        if (diff == null || diff.isBlank()) {
            log.debug("No diff available for scanning - skipping");
            return;
        }

        List<String> logs = new ArrayList<>();
        boolean anyFailed = false;

        for (ReceiveCommand cmd : commands) {
            if (cmd.getType() == ReceiveCommand.Type.DELETE) {
                continue;
            }

            try {
                if (diff.isEmpty()) {
                    logs.add("SKIP: " + cmd.getRefName() + " - empty diff");
                    continue;
                }

                BlockedContentDiffCheck check =
                        new BlockedContentDiffCheck(commitConfig.getDiff().getBlock());
                List<Violation> violations = check.check(diff).orElse(List.of());

                if (!violations.isEmpty()) {
                    for (Violation violation : violations) {
                        validationContext.addIssue("scanDiff", violation.reason(), "ref: " + cmd.getRefName());
                        logs.add("FAIL: " + violation.reason());
                    }
                    anyFailed = true;
                } else {
                    logs.add("PASS: " + cmd.getRefName());
                }

            } catch (Exception e) {
                log.error("Failed to scan diff for {}", cmd.getRefName(), e);
                logs.add("ERROR: " + cmd.getRefName() + " - " + e.getMessage());
            }
        }

        if (!anyFailed) {
            pushContext.addStep(PushStep.builder()
                    .stepName("scanDiff")
                    .stepOrder(ORDER)
                    .status(StepStatus.PASS)
                    .logs(logs)
                    .build());
        }
    }

    @Override
    public int getOrder() {
        return ORDER;
    }

    @Override
    public String getName() {
        return "DiffScanningHook";
    }
}
