package org.finos.gitproxy.git;

import static org.finos.gitproxy.git.GitClient.AnsiColor.*;
import static org.finos.gitproxy.git.GitClient.SymbolCodes.*;
import static org.finos.gitproxy.git.GitClient.color;
import static org.finos.gitproxy.git.GitClient.sym;

import java.util.Collection;
import java.util.List;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.jgit.transport.PreReceiveHook;
import org.eclipse.jgit.transport.ReceiveCommand;
import org.eclipse.jgit.transport.ReceivePack;
import org.finos.gitproxy.config.CommitConfig;
import org.finos.gitproxy.db.model.PushStep;
import org.finos.gitproxy.db.model.StepStatus;
import org.finos.gitproxy.validation.SecretScanCheck;
import org.finos.gitproxy.validation.Violation;

/**
 * S&F-mode adapter for {@link SecretScanCheck}. Reads the diff already generated by {@link DiffGenerationHook} from
 * {@link PushContext}, sends per-finding sideband feedback, and records results in the shared {@link ValidationContext}
 * and {@link PushContext}.
 *
 * <p>If the scanner is unavailable the hook continues (fail-open).
 */
@Slf4j
@RequiredArgsConstructor
public class SecretScanningHook implements PreReceiveHook {

    private static final int STEP_ORDER = 2500;
    private static final String STEP_NAME = "scanSecrets";

    private final CommitConfig.SecretScanningConfig config;
    private final ValidationContext validationContext;
    private final PushContext pushContext;
    private final GitleaksRunner runner;

    public SecretScanningHook(
            CommitConfig.SecretScanningConfig config, ValidationContext validationContext, PushContext pushContext) {
        this(config, validationContext, pushContext, new GitleaksRunner());
    }

    @Override
    public void onPreReceive(ReceivePack rp, Collection<ReceiveCommand> commands) {
        rp.sendMessage(color(CYAN, "[git-proxy] " + sym(KEY) + "  Scanning for secrets..."));

        // Re-use the diff already generated by DiffGenerationHook — scan once for the whole push
        String diff = pushContext
                .getStepContent(DiffGenerationHook.STEP_NAME_PUSH_DIFF)
                .orElse(null);

        var check = new SecretScanCheck(config, runner);
        Optional<List<Violation>> result = check.check(diff);

        if (result.isEmpty()) {
            // Fail-open: scanner unavailable — SecretScanCheck already logged the detail
            rp.sendMessage(color(YELLOW, "[git-proxy]   " + sym(WARNING) + "  Secret scanner unavailable, skipped"));
            // Record a PASS so the step still appears in the UI with a note
            pushContext.addStep(PushStep.builder()
                    .stepName(STEP_NAME)
                    .stepOrder(STEP_ORDER)
                    .status(StepStatus.PASS)
                    .build());
            return;
        }

        List<Violation> violations = result.get();

        if (violations.isEmpty()) {
            rp.sendMessage(color(GREEN, "[git-proxy]   " + sym(HEAVY_CHECK_MARK) + "  No secrets detected"));
            pushContext.addStep(PushStep.builder()
                    .stepName(STEP_NAME)
                    .stepOrder(STEP_ORDER)
                    .status(StepStatus.PASS)
                    .build());
            return;
        }

        for (Violation v : violations) {
            rp.sendMessage(color(RED, "[git-proxy]   " + sym(CROSS_MARK) + "  " + v.subject()));
            validationContext.addIssue(STEP_NAME, v.reason(), v.formattedDetail());
        }
    }
}
