package org.finos.gitproxy.git;

import static org.finos.gitproxy.git.GitClient.AnsiColor.*;
import static org.finos.gitproxy.git.GitClient.SymbolCodes.*;
import static org.finos.gitproxy.git.GitClient.color;
import static org.finos.gitproxy.git.GitClient.sym;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.jgit.transport.PreReceiveHook;
import org.eclipse.jgit.transport.ReceiveCommand;
import org.eclipse.jgit.transport.ReceivePack;
import org.finos.gitproxy.config.CommitConfig;
import org.finos.gitproxy.db.model.PushStep;
import org.finos.gitproxy.db.model.StepStatus;

/**
 * Pre-receive hook that scans the diff of incoming pushes for secrets using gitleaks. Runs after
 * {@link DiffGenerationHook} and re-uses the diff already stored in {@link PushContext} rather than regenerating it.
 *
 * <p>Findings are reported via the sideband channel and recorded in the shared {@link ValidationContext}.
 *
 * <p>If the gitleaks binary is unavailable or execution fails, the hook logs a warning and continues (fail-open).
 * Pushes are never blocked because the scanner is misconfigured.
 */
@Slf4j
@RequiredArgsConstructor
public class SecretScanningHook implements PreReceiveHook {

    private static final String STEP_NAME = "scanSecrets";

    private final CommitConfig.SecretScanningConfig config;
    private final ValidationContext validationContext;
    private final PushContext pushContext;
    private final GitleaksRunner runner;

    /** Convenience constructor; creates a default {@link GitleaksRunner} instance. */
    public SecretScanningHook(
            CommitConfig.SecretScanningConfig config, ValidationContext validationContext, PushContext pushContext) {
        this(config, validationContext, pushContext, new GitleaksRunner());
    }

    @Override
    public void onPreReceive(ReceivePack rp, Collection<ReceiveCommand> commands) {
        if (!config.isEnabled()) {
            log.debug("Secret scanning disabled — skipping");
            return;
        }

        rp.sendMessage(color(CYAN, "[git-proxy] " + sym(KEY) + "  Scanning for secrets..."));

        // Re-use the diff already generated by DiffGenerationHook
        String diff = pushContext
                .getStepContent(DiffGenerationHook.STEP_NAME_PUSH_DIFF)
                .orElse(null);

        if (diff == null || diff.isBlank()) {
            rp.sendMessage(color(
                    YELLOW, "[git-proxy]   " + sym(WARNING) + "  No diff available for secret scanning — skipping"));
            return;
        }

        List<String> logs = new ArrayList<>();
        boolean anyFailed = false;

        for (ReceiveCommand cmd : commands) {
            if (cmd.getType() == ReceiveCommand.Type.DELETE) {
                continue;
            }

            try {
                Optional<List<GitleaksRunner.Finding>> result = runner.scan(diff, config);

                if (result.isEmpty()) {
                    // Fail-open: scanner unavailable or errored
                    rp.sendMessage(color(
                            YELLOW,
                            "[git-proxy]   " + sym(WARNING) + "  " + cmd.getRefName()
                                    + " — secret scanner unavailable, skipped"));
                    logs.add("WARN: " + cmd.getRefName() + " — scanner unavailable");
                    continue;
                }

                List<GitleaksRunner.Finding> findings = result.get();
                if (findings.isEmpty()) {
                    rp.sendMessage(color(
                            GREEN, "[git-proxy]   " + sym(HEAVY_CHECK_MARK) + "  " + cmd.getRefName() + " — clean"));
                    logs.add("PASS: " + cmd.getRefName());
                } else {
                    for (GitleaksRunner.Finding finding : findings) {
                        String message = finding.toMessage();
                        validationContext.addIssue(STEP_NAME, message, "ref: " + cmd.getRefName());
                        rp.sendMessage(color(RED, "[git-proxy]   " + sym(CROSS_MARK) + "  " + message));
                        logs.add("FAIL: " + message);
                    }
                    anyFailed = true;
                }

            } catch (Exception e) {
                log.error("Failed to scan secrets for {}", cmd.getRefName(), e);
                rp.sendMessage(
                        color(YELLOW, "[git-proxy]   " + sym(WARNING) + "  Could not scan secrets: " + e.getMessage()));
                logs.add("ERROR: " + cmd.getRefName() + " — " + e.getMessage());
            }
        }

        pushContext.addStep(PushStep.builder()
                .stepName(STEP_NAME)
                .status(anyFailed ? StepStatus.FAIL : StepStatus.PASS)
                .logs(logs)
                .build());
    }
}
