package org.finos.gitproxy.servlet.filter;

import static org.finos.gitproxy.servlet.GitProxyServlet.GIT_REQUEST_ATTR;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.finos.gitproxy.config.CommitConfig;
import org.finos.gitproxy.db.model.PushStep;
import org.finos.gitproxy.git.DiffGenerationHook;
import org.finos.gitproxy.git.GitRequestDetails;
import org.finos.gitproxy.git.GitleaksRunner;
import org.finos.gitproxy.git.HttpOperation;
import org.finos.gitproxy.validation.SecretScanCheck;
import org.finos.gitproxy.validation.Violation;

/**
 * Proxy-mode adapter for {@link SecretScanCheck}. Reads the diff already generated by {@link ScanDiffFilter} from
 * {@link GitRequestDetails} steps and translates violations into filter-chain rejections.
 *
 * <p>Runs at order 2500, after {@link ScanDiffFilter} (order 2300).
 */
@Slf4j
public class SecretScanningFilter extends AbstractGitProxyFilter {

    private static final int ORDER = 2500;

    private final SecretScanCheck check;

    public SecretScanningFilter(CommitConfig.SecretScanningConfig config, GitleaksRunner runner) {
        super(ORDER, Set.of(HttpOperation.PUSH));
        this.check = new SecretScanCheck(config, runner);
    }

    public SecretScanningFilter(CommitConfig.SecretScanningConfig config) {
        this(config, new GitleaksRunner());
    }

    @Override
    public String getStepName() {
        return "scanSecrets";
    }

    @Override
    public void doHttpFilter(HttpServletRequest request, HttpServletResponse response) throws IOException {
        var requestDetails = (GitRequestDetails) request.getAttribute(GIT_REQUEST_ATTR);
        if (requestDetails == null) {
            log.warn("GitRequestDetails not found in request attributes");
            return;
        }

        // Re-use the diff already generated and stored by ScanDiffFilter
        String diff = requestDetails.getSteps().stream()
                .filter(s -> DiffGenerationHook.STEP_NAME_PUSH_DIFF.equals(s.getStepName()))
                .findFirst()
                .map(PushStep::getContent)
                .orElse(null);

        Optional<List<Violation>> result = check.check(diff);

        if (result.isEmpty()) {
            // Fail-open: scanner unavailable — already logged by SecretScanCheck
            return;
        }

        List<Violation> violations = result.get();
        if (violations.isEmpty()) {
            log.debug("Secret scan passed — no findings");
            return;
        }

        for (Violation v : violations) {
            recordIssue(request, v.reason(), v.formattedDetail());
        }
    }
}
