spring:
  application:
    name: jgit-proxy
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: mappings, health, info
logging:
  level:
    org.finos.gitproxy: INFO
# The below is a minimal configuration needed for the app to start and is the default shipped with the jar.
# By default, the app supports proxying to GitHub, GitLab, and Bitbucket. Users should override this configuration
# to suit their needs.
git-proxy:
#  base-path: "/git"
  providers:
    github:
      enabled: true
    gitlab:
      enabled: true
    bitbucket:
      enabled: true
#    internal-github:
#      enabled: true
#      servlet-path: /enterprise-github
#      uri: https://githubserver.example.com
#    internal-gitlab:
#      enabled: true
#      servlet-path: /external-github
#      uri: https://gitlabserver.other.example.com
    debian-gitlab:
      enabled: true
      servlet-path: /debian
      uri: https://salsa.debian.org/
